version: '3.8'

name: opensilicio

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: opensilicio-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: opensilicio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d opensilicio"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - opensilicio-network

  # Backend API (Node.js + Express)
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: opensilicio-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      # Mount source code for hot-reload
      - ../backend/src:/app/src
      - ../backend/uploads:/app/uploads
      # Cache node_modules to avoid reinstalling on every restart
      - backend_node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/opensilicio
      JWT_SECRET: 8f3c4e2d9a7b6e1f5c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3
      PORT: 3001
      API_URL: http://localhost:3001
      NODE_ENV: development
      CORS_ORIGINS: http://localhost:5173,http://frontend:5173
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - opensilicio-network
    command: sh -c "npm install && npm run dev"

  # Frontend (React + Vite)
  frontend:
    build:
      context: ../openSilicioWebsite
      dockerfile: ../docker/Dockerfile.frontend
    container_name: opensilicio-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot-reload
      - ../openSilicioWebsite/src:/app/src
      - ../openSilicioWebsite/public:/app/public
      # Cache node_modules to avoid reinstalling on every restart
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_URL: http://backend:3001
      NODE_ENV: development
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - opensilicio-network
    command: sh -c "npm install && npm run dev -- --host"

# Named volumes for persistence
volumes:
  postgres_data:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

# Custom network for service communication
networks:
  opensilicio-network:
    driver: bridge

